name: 01-Starter-Workflow
on:
  push:
jobs:
  build:
    runs-on: srini-personal-laptop
    steps:
      - name: Step1
        run: echo "Building Job is executing - Step1"
      - name: Step2
        run: echo "Building Job is executing - Step2"
